[tools]
clojure = "1.12.1"
java = "temurin-21.0.6+7.0.LTS"

[tasks.format]
run = "clojure -M:format"

[tasks.test]
run = "clojure -M:test:repl"

[tasks.antq]
raw = true
run = "clojure -M:antq"

[tasks.repl]
raw = true
run = "clojure -M:test:dev:flowstorm"

[tasks.build]
run = "clojure -T:build jar"

[tasks.clean]
run = "clojure -T:build clean"

[tasks.deploy]
run = "clojure -T:build deploy"

[tasks.fetch-graalvm]
outputs = ["graalvm/graalvm-jdk-21.0.7+8.1"]
run = "[ -d graalvm ] || (mkdir -p graalvm && curl -sSL https://download.oracle.com/graalvm/21/latest/graalvm-jdk-21_linux-x64_bin.tar.gz | tar -vxzC graalvm)"

[tasks.native-image]
depends = ["fetch-graalvm"]
run = ["clojure -M:native-image:repl"]

[env]
_.path = [
  "{{config_root}}/bin",
  "{{config_root}}/graalvm/graalvm-jdk-21.0.7+8.1/bin",
]
